"""Rendering findings as an AGENTS.md, and as machine-readable JSON.

Two principles shape the output:

**Only say what was observed.** A generated file that pads itself with generic
advice ("write clean code", "add tests") trains readers to skim it, which
destroys the value of the specific rules sitting next to the filler. If a
detector found nothing about testing, the Tests section does not exist.

**Mark what is uncertain.** A rule backed by 62% of files is real information
and it is not the same as one backed by 98%. Weakly-evidenced rules render with
their share visible so a human editing the file knows which lines to check
first.
"""

from __future__ import annotations

import json
from typing import Dict, List, Sequence

from .detectors import SECTION_ORDER
from .evidence import Confidence, Finding

__all__ = ["GENERATED_MARKER", "render_json", "render_markdown"]

#: Presence of this marker is how ``--check`` recognizes a file it produced,
#: and how a human recognizes a file they should not hand-edit carelessly.
GENERATED_MARKER = "<!-- agentsmith:generated -->"

HEADER = """# AGENTS.md

%s
Generated by [agentsmith](https://github.com/erickdronski/agentsmith) from what
this repository actually does — every rule below was derived from committed
code, configuration, or git history, not from anyone's recollection.

Run `agentsmith --check` to find out when this file has drifted from reality.
"""


def render_markdown(
    findings: Sequence[Finding],
    repo_name: str,
    explain: bool = False,
    min_confidence: str = Confidence.WEAK,
) -> str:
    kept = [
        finding
        for finding in findings
        if Confidence.rank(finding.confidence) <= Confidence.rank(min_confidence)
    ]

    grouped: Dict[str, List[Finding]] = {}
    for finding in kept:
        grouped.setdefault(finding.section, []).append(finding)

    lines: List[str] = [HEADER % (GENERATED_MARKER + "\n")]

    if not kept:
        lines.append(
            "No conventions could be detected with confidence. That usually "
            "means the repository is very small, very new, or genuinely "
            "inconsistent — in any of those cases, a hand-written file will "
            "serve better than a generated one.\n"
        )
        return "\n".join(lines)

    ordered_sections = [s for s in SECTION_ORDER if s in grouped]
    ordered_sections += sorted(s for s in grouped if s not in SECTION_ORDER)

    for section in ordered_sections:
        lines.append("## %s\n" % section)
        for finding in _order(grouped[section]):
            lines.append(_render_finding(finding, explain))
        lines.append("")

    lines.append("---\n")
    lines.append(
        "_%d rule%s derived from this repository. Rules marked _(seen in N%% "
        "of files)_ are tendencies rather than absolutes — verify those before "
        "relying on them._" % (len(kept), "" if len(kept) == 1 else "s")
    )
    return "\n".join(lines)


def _order(findings: List[Finding]) -> List[Finding]:
    return sorted(findings, key=lambda f: (Confidence.rank(f.confidence), f.key))


def _render_finding(finding: Finding, explain: bool) -> str:
    body = finding.rule
    qualifier = _qualifier(finding)

    if "\n" in body:
        head, _, rest = body.partition("\n")
        text = "- %s%s\n%s" % (head, qualifier, _indent(rest))
    else:
        text = "- %s%s" % (body, qualifier)

    if finding.note:
        text += "\n  _%s_" % finding.note

    if explain and finding.evidence:
        detail = "\n".join(
            "  - `%s` — %s%s"
            % (
                item.source,
                item.summary(),
                (
                    " (e.g. %s)" % ", ".join("`%s`" % s for s in item.samples)
                    if item.samples
                    else ""
                ),
            )
            for item in finding.evidence
        )
        text += (
            "\n  <details><summary>evidence</summary>\n\n%s\n\n  </details>" % detail
        )

    return text + "\n"


def _qualifier(finding: Finding) -> str:
    """Show the share only when the rule is not near-universal."""
    if finding.confidence in (Confidence.CERTAIN, Confidence.STRONG):
        return ""
    for item in finding.evidence:
        if item.share is not None:
            return " _(seen in %.0f%% of files)_" % (item.share * 100)
    return " _(tendency, not a rule)_"


def _indent(text: str) -> str:
    return "\n".join(
        ("  " + line) if line.strip() else line for line in text.splitlines()
    )


def render_json(findings: Sequence[Finding], repo_name: str, version: str) -> str:
    return json.dumps(
        {
            "tool": "agentsmith",
            "version": version,
            "repository": repo_name,
            "finding_count": len(findings),
            "findings": [finding.to_dict() for finding in findings],
        },
        indent=2,
    )
